### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by schwittlick** [SableRaf/signalfilter#1]
Hi @SableRaf,

I can't seem to find the source code for this and thus needed to decompile the class files in the package, but that's very unhandy for applying changes. Would be great if you could quickly push that and I'll be able to work on it a little.

Cheers already,
Marcel

**Comment by SableRaf** [comment]
My bad, here they are: https://github.com/SableRaf/signalfilter/tree/master/src
Thanks for you contribution!

Have a great week end :)
Raphaël

**Comment by schwittlick** [comment]
Cheers <3 You too
